Banking_web_app/Banking_web_app/urls.py
from django.contrib import admin
from django.urls import path,include

import Banking_web_app.settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bank.urls'))
]

Banking_web_app/bank/urls.py
from django.urls import path
from . import views
app_name='bank'
urlpatterns = [
    path('',views.home,name='home'),
    path('cust/',views.user_listview.as_view(),name='list'),
    path('details/<int:pk>',views.user_detailview.as_view(),name='details'),
]

Banking_web_app/bank/models.py
from django.db import models
from django.contrib.auth.models import User,PermissionsMixin
# Create your models here.
class User(models.Model):
    Account_number=models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    email_id=models.EmailField(max_length=100)
    phone_NO=models.CharField(max_length=100)
    address=models.CharField(max_length=100)
    Balance=models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Transfers(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    transfer_amount=models.IntegerField()
    transfer_date=models.DateField()
    transfer_time=models.TimeField()

    def __str__(self):
        return self.transfer_date + "\t " + self.transfer_time

Banking_web_app/bank/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import User
# Create your views here.

def home(request):
    return render(request,'home.html')

class user_listview(ListView):
    model=User
    template_name = 'listview.html'

class user_detailview(DetailView):
    model=User
    template_name = 'detailview.html'
    context_object_name = 'cust'

Banking_web_app/templates/detailview.html
{% extends 'home.html' %}
{% block body %}
    <h1>Customer Details</h1>
    <h2>{{ cust.name }}</h2>
    <p>{{ cust.Account_number }}</p>
{% endblock %}

Banking_web_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BANK SYSTEM</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'bank:list' %}">View all Customers </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>
<div>
    {% block body %}
    {% endblock %}
</div>
<body>

</body>
</html>

Banking_web_app/templates/listview.html
{% extends 'home.html' %}
{% block body %}
    {% for x in user_list %}

            <ul><a href="{% url 'bank:details' pk=x.pk %}">{{ x.name }}</a></ul>

    {% endfor %}

{% endblock %}